#import "~/components/Page/fragment.gql"
#import "~/components/Article/fragment.gql"

query RouterQuery($path: String!) {
  route(path: $path) {
    ... on EntityCanonicalUrl {
      entity {
        ...PageFragment
        ...ArticleFragment
      }
    }
  }
}
