// flow-typed signature: 22b0f6cd3b7f7dfcd5880fa859ee4e89
// flow-typed version: <<STUB>>/apollo-link-batch_v^1.0.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-batch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-batch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-batch/lib/batching' {
  declare module.exports: any;
}

declare module 'apollo-link-batch/lib/batchLink' {
  declare module.exports: any;
}

declare module 'apollo-link-batch/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link-batch/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-link-batch/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-batch/lib/batching.js' {
  declare module.exports: $Exports<'apollo-link-batch/lib/batching'>;
}
declare module 'apollo-link-batch/lib/batchLink.js' {
  declare module.exports: $Exports<'apollo-link-batch/lib/batchLink'>;
}
declare module 'apollo-link-batch/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link-batch/lib/bundle.umd'>;
}
declare module 'apollo-link-batch/lib/index.js' {
  declare module.exports: $Exports<'apollo-link-batch/lib/index'>;
}
declare module 'apollo-link-batch/rollup.config.js' {
  declare module.exports: $Exports<'apollo-link-batch/rollup.config'>;
}
