// flow-typed signature: e0ba3b9e07ead0cedb578ed24b060d97
// flow-typed version: <<STUB>>/aria-query_v0.7.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aria-query'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aria-query' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aria-query/lib/ariaPropsMap' {
  declare module.exports: any;
}

declare module 'aria-query/lib/domMap' {
  declare module.exports: any;
}

declare module 'aria-query/lib/elementRoleMap' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/abstract/commandRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/abstract/compositeRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/abstract/inputRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/abstract/landmarkRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/abstract/rangeRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/abstract/roletypeRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/abstract/sectionheadRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/abstract/sectionRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/abstract/selectRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/abstract/structureRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/abstract/widgetRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/abstract/windowRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/ariaAbstractRoles' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/ariaDpubRoles' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/ariaLiteralRoles' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docAbstractRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docAcknowledgmentsRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docAfterwordRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docAppendixRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docBacklinkRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docBiblioentryRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docBibliographyRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docBibliorefRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docChapterRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docColophonRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docConclusionRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docCoverRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docCreditRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docCreditsRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docDedicationRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docEndnoteRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docEndnotesRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docEpigraphRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docEpilogueRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docErrataRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docExampleRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docFootnoteRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docForewordRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docGlossaryRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docGlossrefRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docIndexRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docIntroductionRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docNoterefRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docNoticeRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docPagebreakRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docPagelistRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docPartRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docPrefaceRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docPrologueRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docPullquoteRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docQnaRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docSubtitleRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docTipRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/dpub/docTocRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/alertdialogRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/alertRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/applicationRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/articleRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/bannerRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/buttonRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/cellRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/checkboxRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/columnheaderRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/comboboxRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/complementaryRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/contentinfoRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/definitionRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/dialogRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/directoryRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/documentRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/feedRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/figureRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/formRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/gridcellRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/gridRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/groupRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/headingRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/imgRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/linkRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/listboxRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/listitemRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/listRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/logRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/mainRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/marqueeRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/mathRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/menubarRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/menuitemcheckboxRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/menuitemradioRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/menuitemRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/menuRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/navigationRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/noneRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/noteRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/optionRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/presentationRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/progressbarRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/radiogroupRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/radioRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/regionRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/rowgroupRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/rowheaderRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/rowRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/scrollbarRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/searchboxRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/searchRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/separatorRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/sliderRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/spinbuttonRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/statusRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/switchRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/tableRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/tablistRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/tabpanelRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/tabRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/termRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/textboxRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/timerRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/toolbarRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/tooltipRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/treegridRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/treeitemRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/etc/roles/literal/treeRole' {
  declare module.exports: any;
}

declare module 'aria-query/lib/index' {
  declare module.exports: any;
}

declare module 'aria-query/lib/roleElementMap' {
  declare module.exports: any;
}

declare module 'aria-query/lib/rolesMap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aria-query/lib/ariaPropsMap.js' {
  declare module.exports: $Exports<'aria-query/lib/ariaPropsMap'>;
}
declare module 'aria-query/lib/domMap.js' {
  declare module.exports: $Exports<'aria-query/lib/domMap'>;
}
declare module 'aria-query/lib/elementRoleMap.js' {
  declare module.exports: $Exports<'aria-query/lib/elementRoleMap'>;
}
declare module 'aria-query/lib/etc/roles/abstract/commandRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/abstract/commandRole'>;
}
declare module 'aria-query/lib/etc/roles/abstract/compositeRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/abstract/compositeRole'>;
}
declare module 'aria-query/lib/etc/roles/abstract/inputRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/abstract/inputRole'>;
}
declare module 'aria-query/lib/etc/roles/abstract/landmarkRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/abstract/landmarkRole'>;
}
declare module 'aria-query/lib/etc/roles/abstract/rangeRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/abstract/rangeRole'>;
}
declare module 'aria-query/lib/etc/roles/abstract/roletypeRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/abstract/roletypeRole'>;
}
declare module 'aria-query/lib/etc/roles/abstract/sectionheadRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/abstract/sectionheadRole'>;
}
declare module 'aria-query/lib/etc/roles/abstract/sectionRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/abstract/sectionRole'>;
}
declare module 'aria-query/lib/etc/roles/abstract/selectRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/abstract/selectRole'>;
}
declare module 'aria-query/lib/etc/roles/abstract/structureRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/abstract/structureRole'>;
}
declare module 'aria-query/lib/etc/roles/abstract/widgetRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/abstract/widgetRole'>;
}
declare module 'aria-query/lib/etc/roles/abstract/windowRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/abstract/windowRole'>;
}
declare module 'aria-query/lib/etc/roles/ariaAbstractRoles.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/ariaAbstractRoles'>;
}
declare module 'aria-query/lib/etc/roles/ariaDpubRoles.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/ariaDpubRoles'>;
}
declare module 'aria-query/lib/etc/roles/ariaLiteralRoles.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/ariaLiteralRoles'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docAbstractRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docAbstractRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docAcknowledgmentsRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docAcknowledgmentsRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docAfterwordRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docAfterwordRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docAppendixRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docAppendixRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docBacklinkRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docBacklinkRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docBiblioentryRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docBiblioentryRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docBibliographyRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docBibliographyRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docBibliorefRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docBibliorefRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docChapterRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docChapterRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docColophonRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docColophonRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docConclusionRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docConclusionRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docCoverRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docCoverRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docCreditRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docCreditRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docCreditsRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docCreditsRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docDedicationRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docDedicationRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docEndnoteRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docEndnoteRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docEndnotesRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docEndnotesRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docEpigraphRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docEpigraphRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docEpilogueRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docEpilogueRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docErrataRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docErrataRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docExampleRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docExampleRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docFootnoteRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docFootnoteRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docForewordRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docForewordRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docGlossaryRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docGlossaryRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docGlossrefRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docGlossrefRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docIndexRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docIndexRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docIntroductionRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docIntroductionRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docNoterefRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docNoterefRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docNoticeRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docNoticeRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docPagebreakRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docPagebreakRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docPagelistRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docPagelistRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docPartRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docPartRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docPrefaceRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docPrefaceRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docPrologueRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docPrologueRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docPullquoteRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docPullquoteRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docQnaRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docQnaRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docSubtitleRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docSubtitleRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docTipRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docTipRole'>;
}
declare module 'aria-query/lib/etc/roles/dpub/docTocRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/dpub/docTocRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/alertdialogRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/alertdialogRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/alertRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/alertRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/applicationRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/applicationRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/articleRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/articleRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/bannerRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/bannerRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/buttonRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/buttonRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/cellRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/cellRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/checkboxRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/checkboxRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/columnheaderRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/columnheaderRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/comboboxRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/comboboxRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/complementaryRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/complementaryRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/contentinfoRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/contentinfoRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/definitionRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/definitionRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/dialogRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/dialogRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/directoryRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/directoryRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/documentRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/documentRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/feedRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/feedRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/figureRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/figureRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/formRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/formRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/gridcellRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/gridcellRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/gridRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/gridRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/groupRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/groupRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/headingRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/headingRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/imgRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/imgRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/linkRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/linkRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/listboxRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/listboxRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/listitemRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/listitemRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/listRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/listRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/logRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/logRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/mainRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/mainRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/marqueeRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/marqueeRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/mathRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/mathRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/menubarRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/menubarRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/menuitemcheckboxRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/menuitemcheckboxRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/menuitemradioRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/menuitemradioRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/menuitemRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/menuitemRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/menuRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/menuRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/navigationRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/navigationRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/noneRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/noneRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/noteRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/noteRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/optionRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/optionRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/presentationRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/presentationRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/progressbarRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/progressbarRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/radiogroupRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/radiogroupRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/radioRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/radioRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/regionRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/regionRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/rowgroupRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/rowgroupRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/rowheaderRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/rowheaderRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/rowRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/rowRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/scrollbarRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/scrollbarRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/searchboxRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/searchboxRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/searchRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/searchRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/separatorRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/separatorRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/sliderRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/sliderRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/spinbuttonRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/spinbuttonRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/statusRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/statusRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/switchRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/switchRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/tableRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/tableRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/tablistRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/tablistRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/tabpanelRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/tabpanelRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/tabRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/tabRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/termRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/termRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/textboxRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/textboxRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/timerRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/timerRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/toolbarRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/toolbarRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/tooltipRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/tooltipRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/treegridRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/treegridRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/treeitemRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/treeitemRole'>;
}
declare module 'aria-query/lib/etc/roles/literal/treeRole.js' {
  declare module.exports: $Exports<'aria-query/lib/etc/roles/literal/treeRole'>;
}
declare module 'aria-query/lib/index.js' {
  declare module.exports: $Exports<'aria-query/lib/index'>;
}
declare module 'aria-query/lib/roleElementMap.js' {
  declare module.exports: $Exports<'aria-query/lib/roleElementMap'>;
}
declare module 'aria-query/lib/rolesMap.js' {
  declare module.exports: $Exports<'aria-query/lib/rolesMap'>;
}
