// flow-typed signature: eedd1bd03ed4301e3ba57e6d97856d2e
// flow-typed version: <<STUB>>/jsx-ast-utils_v1.4.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsx-ast-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsx-ast-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsx-ast-utils/__tests__/helper' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/__tests__/src/elementType-test' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/__tests__/src/eventHandlers-test' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/__tests__/src/getProp-test' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/__tests__/src/getPropLiteralValue-test' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/__tests__/src/getPropValue-test' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/__tests__/src/hasProp-test' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/__tests__/src/index-test' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/__tests__/src/propName-test' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/elementType' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/eventHandlers' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/eventHandlersByType' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/getLiteralPropValue' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/getProp' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/getPropValue' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/hasAnyProp' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/hasEveryProp' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/hasProp' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/elementType' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/eventHandlers' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/getProp' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/getPropValue' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/hasProp' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/index' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/propName' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/ArrayExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/BinaryExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/CallExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/ConditionalExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/FunctionExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/Identifier' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/index' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/LogicalExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/MemberExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/NewExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/ObjectExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/TaggedTemplateExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/TemplateLiteral' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/ThisExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/UnaryExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/expressions/UpdateExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/index' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/JSXElement' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/lib/values/Literal' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/propName' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/elementType' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/eventHandlers' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/getProp' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/getPropValue' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/hasProp' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/index' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/propName' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/ArrayExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/BinaryExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/CallExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/ConditionalExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/FunctionExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/Identifier' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/index' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/LogicalExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/MemberExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/NewExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/ObjectExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/TaggedTemplateExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/TemplateLiteral' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/ThisExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/UnaryExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/expressions/UpdateExpression' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/index' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/JSXElement' {
  declare module.exports: any;
}

declare module 'jsx-ast-utils/src/values/Literal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsx-ast-utils/__tests__/helper.js' {
  declare module.exports: $Exports<'jsx-ast-utils/__tests__/helper'>;
}
declare module 'jsx-ast-utils/__tests__/src/elementType-test.js' {
  declare module.exports: $Exports<'jsx-ast-utils/__tests__/src/elementType-test'>;
}
declare module 'jsx-ast-utils/__tests__/src/eventHandlers-test.js' {
  declare module.exports: $Exports<'jsx-ast-utils/__tests__/src/eventHandlers-test'>;
}
declare module 'jsx-ast-utils/__tests__/src/getProp-test.js' {
  declare module.exports: $Exports<'jsx-ast-utils/__tests__/src/getProp-test'>;
}
declare module 'jsx-ast-utils/__tests__/src/getPropLiteralValue-test.js' {
  declare module.exports: $Exports<'jsx-ast-utils/__tests__/src/getPropLiteralValue-test'>;
}
declare module 'jsx-ast-utils/__tests__/src/getPropValue-test.js' {
  declare module.exports: $Exports<'jsx-ast-utils/__tests__/src/getPropValue-test'>;
}
declare module 'jsx-ast-utils/__tests__/src/hasProp-test.js' {
  declare module.exports: $Exports<'jsx-ast-utils/__tests__/src/hasProp-test'>;
}
declare module 'jsx-ast-utils/__tests__/src/index-test.js' {
  declare module.exports: $Exports<'jsx-ast-utils/__tests__/src/index-test'>;
}
declare module 'jsx-ast-utils/__tests__/src/propName-test.js' {
  declare module.exports: $Exports<'jsx-ast-utils/__tests__/src/propName-test'>;
}
declare module 'jsx-ast-utils/elementType.js' {
  declare module.exports: $Exports<'jsx-ast-utils/elementType'>;
}
declare module 'jsx-ast-utils/eventHandlers.js' {
  declare module.exports: $Exports<'jsx-ast-utils/eventHandlers'>;
}
declare module 'jsx-ast-utils/eventHandlersByType.js' {
  declare module.exports: $Exports<'jsx-ast-utils/eventHandlersByType'>;
}
declare module 'jsx-ast-utils/getLiteralPropValue.js' {
  declare module.exports: $Exports<'jsx-ast-utils/getLiteralPropValue'>;
}
declare module 'jsx-ast-utils/getProp.js' {
  declare module.exports: $Exports<'jsx-ast-utils/getProp'>;
}
declare module 'jsx-ast-utils/getPropValue.js' {
  declare module.exports: $Exports<'jsx-ast-utils/getPropValue'>;
}
declare module 'jsx-ast-utils/hasAnyProp.js' {
  declare module.exports: $Exports<'jsx-ast-utils/hasAnyProp'>;
}
declare module 'jsx-ast-utils/hasEveryProp.js' {
  declare module.exports: $Exports<'jsx-ast-utils/hasEveryProp'>;
}
declare module 'jsx-ast-utils/hasProp.js' {
  declare module.exports: $Exports<'jsx-ast-utils/hasProp'>;
}
declare module 'jsx-ast-utils/lib/elementType.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/elementType'>;
}
declare module 'jsx-ast-utils/lib/eventHandlers.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/eventHandlers'>;
}
declare module 'jsx-ast-utils/lib/getProp.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/getProp'>;
}
declare module 'jsx-ast-utils/lib/getPropValue.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/getPropValue'>;
}
declare module 'jsx-ast-utils/lib/hasProp.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/hasProp'>;
}
declare module 'jsx-ast-utils/lib/index.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/index'>;
}
declare module 'jsx-ast-utils/lib/propName.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/propName'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/ArrayExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/ArrayExpression'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/BinaryExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/BinaryExpression'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/CallExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/CallExpression'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/ConditionalExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/ConditionalExpression'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/FunctionExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/FunctionExpression'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/Identifier.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/Identifier'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/index.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/index'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/LogicalExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/LogicalExpression'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/MemberExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/MemberExpression'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/NewExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/NewExpression'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/ObjectExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/ObjectExpression'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/TaggedTemplateExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/TaggedTemplateExpression'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/TemplateLiteral.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/TemplateLiteral'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/ThisExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/ThisExpression'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/UnaryExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/UnaryExpression'>;
}
declare module 'jsx-ast-utils/lib/values/expressions/UpdateExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/expressions/UpdateExpression'>;
}
declare module 'jsx-ast-utils/lib/values/index.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/index'>;
}
declare module 'jsx-ast-utils/lib/values/JSXElement.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/JSXElement'>;
}
declare module 'jsx-ast-utils/lib/values/Literal.js' {
  declare module.exports: $Exports<'jsx-ast-utils/lib/values/Literal'>;
}
declare module 'jsx-ast-utils/propName.js' {
  declare module.exports: $Exports<'jsx-ast-utils/propName'>;
}
declare module 'jsx-ast-utils/src/elementType.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/elementType'>;
}
declare module 'jsx-ast-utils/src/eventHandlers.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/eventHandlers'>;
}
declare module 'jsx-ast-utils/src/getProp.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/getProp'>;
}
declare module 'jsx-ast-utils/src/getPropValue.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/getPropValue'>;
}
declare module 'jsx-ast-utils/src/hasProp.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/hasProp'>;
}
declare module 'jsx-ast-utils/src/index.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/index'>;
}
declare module 'jsx-ast-utils/src/propName.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/propName'>;
}
declare module 'jsx-ast-utils/src/values/expressions/ArrayExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/ArrayExpression'>;
}
declare module 'jsx-ast-utils/src/values/expressions/BinaryExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/BinaryExpression'>;
}
declare module 'jsx-ast-utils/src/values/expressions/CallExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/CallExpression'>;
}
declare module 'jsx-ast-utils/src/values/expressions/ConditionalExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/ConditionalExpression'>;
}
declare module 'jsx-ast-utils/src/values/expressions/FunctionExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/FunctionExpression'>;
}
declare module 'jsx-ast-utils/src/values/expressions/Identifier.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/Identifier'>;
}
declare module 'jsx-ast-utils/src/values/expressions/index.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/index'>;
}
declare module 'jsx-ast-utils/src/values/expressions/LogicalExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/LogicalExpression'>;
}
declare module 'jsx-ast-utils/src/values/expressions/MemberExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/MemberExpression'>;
}
declare module 'jsx-ast-utils/src/values/expressions/NewExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/NewExpression'>;
}
declare module 'jsx-ast-utils/src/values/expressions/ObjectExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/ObjectExpression'>;
}
declare module 'jsx-ast-utils/src/values/expressions/TaggedTemplateExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/TaggedTemplateExpression'>;
}
declare module 'jsx-ast-utils/src/values/expressions/TemplateLiteral.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/TemplateLiteral'>;
}
declare module 'jsx-ast-utils/src/values/expressions/ThisExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/ThisExpression'>;
}
declare module 'jsx-ast-utils/src/values/expressions/UnaryExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/UnaryExpression'>;
}
declare module 'jsx-ast-utils/src/values/expressions/UpdateExpression.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/expressions/UpdateExpression'>;
}
declare module 'jsx-ast-utils/src/values/index.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/index'>;
}
declare module 'jsx-ast-utils/src/values/JSXElement.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/JSXElement'>;
}
declare module 'jsx-ast-utils/src/values/Literal.js' {
  declare module.exports: $Exports<'jsx-ast-utils/src/values/Literal'>;
}
