// flow-typed signature: 6b874024a17342e372060195ec9d55d5
// flow-typed version: <<STUB>>/persistgraphql_v^0.3.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'persistgraphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'persistgraphql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'persistgraphql/lib/browser' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/index' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/server' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/binary' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/common' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/extractFromAST' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/extractFromJS' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/ExtractGQL' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/index' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/network_interface/ApolloNetworkInterface' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/queryTransformers' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/server/serverUtil' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/test/extractFromAST' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/test/extractFromJS' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/test/index' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/test/network_interface/ApolloNetworkInterface' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/test/queryTransformers' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/test/server/serverUtil' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/test/tests' {
  declare module.exports: any;
}

declare module 'persistgraphql/test/fixtures/single_fragment_js/code' {
  declare module.exports: any;
}

// Filename aliases
declare module 'persistgraphql/lib/browser.js' {
  declare module.exports: $Exports<'persistgraphql/lib/browser'>;
}
declare module 'persistgraphql/lib/index.js' {
  declare module.exports: $Exports<'persistgraphql/lib/index'>;
}
declare module 'persistgraphql/lib/server.js' {
  declare module.exports: $Exports<'persistgraphql/lib/server'>;
}
declare module 'persistgraphql/lib/src/binary.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/binary'>;
}
declare module 'persistgraphql/lib/src/common.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/common'>;
}
declare module 'persistgraphql/lib/src/extractFromAST.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/extractFromAST'>;
}
declare module 'persistgraphql/lib/src/extractFromJS.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/extractFromJS'>;
}
declare module 'persistgraphql/lib/src/ExtractGQL.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/ExtractGQL'>;
}
declare module 'persistgraphql/lib/src/index.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/index'>;
}
declare module 'persistgraphql/lib/src/network_interface/ApolloNetworkInterface.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/network_interface/ApolloNetworkInterface'>;
}
declare module 'persistgraphql/lib/src/queryTransformers.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/queryTransformers'>;
}
declare module 'persistgraphql/lib/src/server/serverUtil.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/server/serverUtil'>;
}
declare module 'persistgraphql/lib/test/extractFromAST.js' {
  declare module.exports: $Exports<'persistgraphql/lib/test/extractFromAST'>;
}
declare module 'persistgraphql/lib/test/extractFromJS.js' {
  declare module.exports: $Exports<'persistgraphql/lib/test/extractFromJS'>;
}
declare module 'persistgraphql/lib/test/index.js' {
  declare module.exports: $Exports<'persistgraphql/lib/test/index'>;
}
declare module 'persistgraphql/lib/test/network_interface/ApolloNetworkInterface.js' {
  declare module.exports: $Exports<'persistgraphql/lib/test/network_interface/ApolloNetworkInterface'>;
}
declare module 'persistgraphql/lib/test/queryTransformers.js' {
  declare module.exports: $Exports<'persistgraphql/lib/test/queryTransformers'>;
}
declare module 'persistgraphql/lib/test/server/serverUtil.js' {
  declare module.exports: $Exports<'persistgraphql/lib/test/server/serverUtil'>;
}
declare module 'persistgraphql/lib/test/tests.js' {
  declare module.exports: $Exports<'persistgraphql/lib/test/tests'>;
}
declare module 'persistgraphql/test/fixtures/single_fragment_js/code.js' {
  declare module.exports: $Exports<'persistgraphql/test/fixtures/single_fragment_js/code'>;
}
