// flow-typed signature: 01525019e485bc2acb4343c753f2208c
// flow-typed version: <<STUB>>/react-router-preload-tree_v^0.0.4/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-preload-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-preload-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-preload-tree/lib/index.cjs' {
  declare module.exports: any;
}

declare module 'react-router-preload-tree/lib/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-preload-tree/lib/index.cjs.js' {
  declare module.exports: $Exports<'react-router-preload-tree/lib/index.cjs'>;
}
declare module 'react-router-preload-tree/lib/index.esm.js' {
  declare module.exports: $Exports<'react-router-preload-tree/lib/index.esm'>;
}
