// flow-typed signature: 0840b4cf575c40e0f3ab8b940b753f24
// flow-typed version: <<STUB>>/react-tree-walker_v^2.1.2/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tree-walker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tree-walker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tree-walker/commonjs/index' {
  declare module.exports: any;
}

declare module 'react-tree-walker/umd/react-tree-walker' {
  declare module.exports: any;
}

declare module 'react-tree-walker/umd/react-tree-walker.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tree-walker/commonjs/index.js' {
  declare module.exports: $Exports<'react-tree-walker/commonjs/index'>;
}
declare module 'react-tree-walker/umd/react-tree-walker.js' {
  declare module.exports: $Exports<'react-tree-walker/umd/react-tree-walker'>;
}
declare module 'react-tree-walker/umd/react-tree-walker.min.js' {
  declare module.exports: $Exports<'react-tree-walker/umd/react-tree-walker.min'>;
}
