// flow-typed signature: 117938f86e51915016fbbd4707357ae4
// flow-typed version: <<STUB>>/react-universal-component_v1.4.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-universal-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-universal-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-universal-component/dist/index' {
  declare module.exports: any;
}

declare module 'react-universal-component/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-universal-component/dist/index.js' {
  declare module.exports: $Exports<'react-universal-component/dist/index'>;
}
declare module 'react-universal-component/server.js' {
  declare module.exports: $Exports<'react-universal-component/server'>;
}
