// flow-typed signature: a0e326dcffa269e7a0642caeb7010ff4
// flow-typed version: <<STUB>>/react-preload-apollo_v^0.0.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-preload-apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-preload-apollo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-preload-apollo/lib/index.cjs' {
  declare module.exports: any;
}

declare module 'react-preload-apollo/lib/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-preload-apollo/lib/index.cjs.js' {
  declare module.exports: $Exports<'react-preload-apollo/lib/index.cjs'>;
}
declare module 'react-preload-apollo/lib/index.esm.js' {
  declare module.exports: $Exports<'react-preload-apollo/lib/index.esm'>;
}
