// flow-typed signature: 9497fe3c50a819fcc5fc7e6ab2648868
// flow-typed version: <<STUB>>/require-universal-module_v1.5.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'require-universal-module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'require-universal-module' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'require-universal-module/__fixtures__/es5' {
  declare module.exports: any;
}

declare module 'require-universal-module/__fixtures__/es6' {
  declare module.exports: any;
}

declare module 'require-universal-module/dist/index' {
  declare module.exports: any;
}

declare module 'require-universal-module/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'require-universal-module/__fixtures__/es5.js' {
  declare module.exports: $Exports<'require-universal-module/__fixtures__/es5'>;
}
declare module 'require-universal-module/__fixtures__/es6.js' {
  declare module.exports: $Exports<'require-universal-module/__fixtures__/es6'>;
}
declare module 'require-universal-module/dist/index.js' {
  declare module.exports: $Exports<'require-universal-module/dist/index'>;
}
declare module 'require-universal-module/server.js' {
  declare module.exports: $Exports<'require-universal-module/server'>;
}
