// flow-typed signature: 9dbbae6e8b650f7f0c2c63b9e431673f
// flow-typed version: <<STUB>>/serialize-javascript_v^1.3.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serialize-javascript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serialize-javascript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'serialize-javascript/index' {
  declare module.exports: $Exports<'serialize-javascript'>;
}
declare module 'serialize-javascript/index.js' {
  declare module.exports: $Exports<'serialize-javascript'>;
}
