// flow-typed signature: dd1d10cd29c9eea58cf2f8360b1b4cff
// flow-typed version: <<STUB>>/webpack-flush-chunks_v1.1.10/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-flush-chunks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-flush-chunks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-flush-chunks/dist/createApiWithCss' {
  declare module.exports: any;
}

declare module 'webpack-flush-chunks/dist/flushChunks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-flush-chunks/dist/createApiWithCss.js' {
  declare module.exports: $Exports<'webpack-flush-chunks/dist/createApiWithCss'>;
}
declare module 'webpack-flush-chunks/dist/flushChunks.js' {
  declare module.exports: $Exports<'webpack-flush-chunks/dist/flushChunks'>;
}
