#!/bin/bash

# get changed files
CHANGED="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"
SHOULD_REINSTALL=0

# check if packages have been updated
for file in $CHANGED; do
  if [[ $file == "yarn.lock" ]]
  then
    SHOULD_REINSTALL=1
  elif [[ $file == internals/eslint/* ]]
  then
    SHOULD_REINSTALL=1
    rm -rf node_modules/eslint-plugin-ras/
    break
  fi
done

if [[ $SHOULD_REINSTALL == 1 ]]
then
  echo "---------------------------------------------------------------------------------------"

  # Allows us to read user input below, assigns stdin to keyboard.
  exec < /dev/tty

  while true; do
    read -r -p "Packages have changed, do you want to re-install your dependencies now? [Y/n]: " response
    if [ "$response" = "" ]; then
      response='Y'
    fi

    case $response in
      [Yy] ) yarn install; break;;
      [Nn] ) exit;;
      * ) echo "Please answer \"y\" or \"n\" for \"yes\" or \"no\".";;
    esac
  done
fi
