// flow-typed signature: 0715774303037737625a6054b73be655
// flow-typed version: <<STUB>>/@amazee/paraplegie_v1.0.10/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@amazee/paraplegie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@amazee/paraplegie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@amazee/paraplegie/lib/js/app/Config' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/BaseMap' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/BaseModule' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/cms/FloatingQuote' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/cms/HeaderSlider' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/cms/HomeSlider' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/cms/ImageSlider' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/cms/InlineMap' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/cms/InlineTabs' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/cms/Slider' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/cms/SubpageHeader' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/form/InputDate' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/global/MobileNav' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/global/SiteHeader' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/global/SiteHeader/SiteHeaderNav' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/global/SiteHeader/SiteHeaderSticky' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/global/SiteSearch' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/global/Skiplinks' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/maps/HTMLMarker' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/utils/Collapsible' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/utils/Cover' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/utils/HoverGroup' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/utils/PhotoSwipeController' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/utils/ScrollSlider' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/utils/ScrollSpy' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/utils/SmoothScroll' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/modules/utils/Sticky' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/plugins' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/plugins/fixedsticky.jquery' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/plugins/mediaDispatcher' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/plugins/prepareTransition.jquery' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/app/polyfills' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/animation/AnimationFrame' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/animation/HeightAnimation' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/animation/scrollToView' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/browser/Accessibility' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/browser/ClickSpot' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/browser/FlyingFocus' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/browser/KeepFocus' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/browser/KeyCodes' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/browser/MediaDispatcher' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/browser/Pointer' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/browser/ScrollParent' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/net/GoogleMapsAPILoader' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/util/contextTrigger' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/util/DeferredBoolean' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/util/DeferredState' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/util/EventDispatcher' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/util/EventObserver' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/util/loaded-jquery' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/util/MicroTemplate' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/util/ModuleManager' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/lib/util/Templates' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/ui' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/vendor/almond' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/vendor/headroom' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/vendor/jquery' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/vendor/photoswipe-ui-default' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/vendor/photoswipe' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/vendor/pikaday' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/vendor/polyfills/picturefill' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/vendor/require' {
  declare module.exports: any;
}

declare module '@amazee/paraplegie/lib/js/vendor/swiper.custom' {
  declare module.exports: any;
}

// Filename aliases
declare module '@amazee/paraplegie/lib/js/app/Config.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/Config'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/BaseMap.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/BaseMap'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/BaseModule.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/BaseModule'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/cms/FloatingQuote.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/cms/FloatingQuote'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/cms/HeaderSlider.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/cms/HeaderSlider'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/cms/HomeSlider.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/cms/HomeSlider'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/cms/ImageSlider.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/cms/ImageSlider'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/cms/InlineMap.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/cms/InlineMap'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/cms/InlineTabs.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/cms/InlineTabs'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/cms/Slider.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/cms/Slider'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/cms/SubpageHeader.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/cms/SubpageHeader'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/form/InputDate.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/form/InputDate'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/global/MobileNav.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/global/MobileNav'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/global/SiteHeader.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/global/SiteHeader'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/global/SiteHeader/SiteHeaderNav.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/global/SiteHeader/SiteHeaderNav'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/global/SiteHeader/SiteHeaderSticky.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/global/SiteHeader/SiteHeaderSticky'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/global/SiteSearch.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/global/SiteSearch'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/global/Skiplinks.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/global/Skiplinks'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/maps/HTMLMarker.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/maps/HTMLMarker'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/utils/Collapsible.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/utils/Collapsible'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/utils/Cover.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/utils/Cover'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/utils/HoverGroup.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/utils/HoverGroup'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/utils/PhotoSwipeController.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/utils/PhotoSwipeController'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/utils/ScrollSlider.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/utils/ScrollSlider'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/utils/ScrollSpy.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/utils/ScrollSpy'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/utils/SmoothScroll.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/utils/SmoothScroll'>;
}
declare module '@amazee/paraplegie/lib/js/app/modules/utils/Sticky.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/modules/utils/Sticky'>;
}
declare module '@amazee/paraplegie/lib/js/app/plugins.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/plugins'>;
}
declare module '@amazee/paraplegie/lib/js/app/plugins/fixedsticky.jquery.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/plugins/fixedsticky.jquery'>;
}
declare module '@amazee/paraplegie/lib/js/app/plugins/mediaDispatcher.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/plugins/mediaDispatcher'>;
}
declare module '@amazee/paraplegie/lib/js/app/plugins/prepareTransition.jquery.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/plugins/prepareTransition.jquery'>;
}
declare module '@amazee/paraplegie/lib/js/app/polyfills.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/app/polyfills'>;
}
declare module '@amazee/paraplegie/lib/js/lib/animation/AnimationFrame.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/animation/AnimationFrame'>;
}
declare module '@amazee/paraplegie/lib/js/lib/animation/HeightAnimation.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/animation/HeightAnimation'>;
}
declare module '@amazee/paraplegie/lib/js/lib/animation/scrollToView.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/animation/scrollToView'>;
}
declare module '@amazee/paraplegie/lib/js/lib/browser/Accessibility.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/browser/Accessibility'>;
}
declare module '@amazee/paraplegie/lib/js/lib/browser/ClickSpot.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/browser/ClickSpot'>;
}
declare module '@amazee/paraplegie/lib/js/lib/browser/FlyingFocus.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/browser/FlyingFocus'>;
}
declare module '@amazee/paraplegie/lib/js/lib/browser/KeepFocus.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/browser/KeepFocus'>;
}
declare module '@amazee/paraplegie/lib/js/lib/browser/KeyCodes.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/browser/KeyCodes'>;
}
declare module '@amazee/paraplegie/lib/js/lib/browser/MediaDispatcher.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/browser/MediaDispatcher'>;
}
declare module '@amazee/paraplegie/lib/js/lib/browser/Pointer.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/browser/Pointer'>;
}
declare module '@amazee/paraplegie/lib/js/lib/browser/ScrollParent.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/browser/ScrollParent'>;
}
declare module '@amazee/paraplegie/lib/js/lib/net/GoogleMapsAPILoader.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/net/GoogleMapsAPILoader'>;
}
declare module '@amazee/paraplegie/lib/js/lib/util/contextTrigger.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/util/contextTrigger'>;
}
declare module '@amazee/paraplegie/lib/js/lib/util/DeferredBoolean.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/util/DeferredBoolean'>;
}
declare module '@amazee/paraplegie/lib/js/lib/util/DeferredState.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/util/DeferredState'>;
}
declare module '@amazee/paraplegie/lib/js/lib/util/EventDispatcher.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/util/EventDispatcher'>;
}
declare module '@amazee/paraplegie/lib/js/lib/util/EventObserver.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/util/EventObserver'>;
}
declare module '@amazee/paraplegie/lib/js/lib/util/loaded-jquery.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/util/loaded-jquery'>;
}
declare module '@amazee/paraplegie/lib/js/lib/util/MicroTemplate.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/util/MicroTemplate'>;
}
declare module '@amazee/paraplegie/lib/js/lib/util/ModuleManager.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/util/ModuleManager'>;
}
declare module '@amazee/paraplegie/lib/js/lib/util/Templates.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/lib/util/Templates'>;
}
declare module '@amazee/paraplegie/lib/js/ui.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/ui'>;
}
declare module '@amazee/paraplegie/lib/js/vendor/almond.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/vendor/almond'>;
}
declare module '@amazee/paraplegie/lib/js/vendor/headroom.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/vendor/headroom'>;
}
declare module '@amazee/paraplegie/lib/js/vendor/jquery.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/vendor/jquery'>;
}
declare module '@amazee/paraplegie/lib/js/vendor/photoswipe-ui-default.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/vendor/photoswipe-ui-default'>;
}
declare module '@amazee/paraplegie/lib/js/vendor/photoswipe.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/vendor/photoswipe'>;
}
declare module '@amazee/paraplegie/lib/js/vendor/pikaday.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/vendor/pikaday'>;
}
declare module '@amazee/paraplegie/lib/js/vendor/polyfills/picturefill.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/vendor/polyfills/picturefill'>;
}
declare module '@amazee/paraplegie/lib/js/vendor/require.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/vendor/require'>;
}
declare module '@amazee/paraplegie/lib/js/vendor/swiper.custom.js' {
  declare module.exports: $Exports<'@amazee/paraplegie/lib/js/vendor/swiper.custom'>;
}
